[WIP] Create bundle_uk_UA.properties
TheSlaylord/GoldMod pull request #12
Opened 2020-07-05 19:06 UTC by Prosta4okua

2020-07-05 19:07 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +liquid.goldmod-moltenGold.name = Плавелене золото
@Prosta4okua жахливий перекладач!

2020-07-05 19:07 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +liquid.goldmod-moltenGold.description = Плавлена золота руда Використвується у виробництві або як прискорювач у поліпшених баштах.
----

2020-07-06 09:51 UTC, Slotterleet reviewed
Просто кину сюда, на всякий случай.
29 строка

2020-07-06 09:53 UTC, Slotterleet reviewed
Просто кину сюда, на всякий случай.

2020-08-09 05:06 UTC, Slotterleet requested changes

2020-08-09 05:06 UTC, TheSlaylord commented on bundles/bundle_uk_UA.properties
> +block.goldmod-goldмe.name = Золотий підривник
goldмe?

2020-08-09 13:42 UTC, Prosta4okua commented
@TheSlaylord what should I do?

2020-08-09 15:20 UTC, merged